// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: printable.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2018-2022 The MobileCoin Foundation

/// Protos to be used for displaying encoded strings to users

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

//// Message for a payment request, which combines a public address
//// with an a requested payment amount and memo field
public struct Printable_PaymentRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// The public address of the user requesting a payment
  public var publicAddress: External_PublicAddress {
    get {_publicAddress ?? External_PublicAddress()}
    set {_publicAddress = newValue}
  }
  /// Returns true if `publicAddress` has been explicitly set.
  public var hasPublicAddress: Bool {self._publicAddress != nil}
  /// Clears the value of `publicAddress`. Subsequent reads from it will return its default value.
  public mutating func clearPublicAddress() {self._publicAddress = nil}

  //// The requested value of the payment
  public var value: UInt64 = 0

  //// Any additional text explaining the request
  public var memo: String = String()

  //// Token id to transact in.
  public var tokenID: UInt64 = 0

  //// Payment Id
  public var paymentID: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _publicAddress: External_PublicAddress? = nil
}

//// Message encoding a private key and a UTXO, for the purpose of
//// giving someone access to an output. This would most likely be
//// used for gift cards.
public struct Printable_TransferPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  //// [Deprecated] The root entropy, allowing the recipient to spend the money.
  //// This has been replaced by a BIP39 entropy.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  public var rootEntropy: Data = Data()

  //// The public key of the UTXO to spend. This is an optimization, meaning
  //// the recipient does not need to scan the entire ledger.
  public var txOutPublicKey: External_CompressedRistretto {
    get {_txOutPublicKey ?? External_CompressedRistretto()}
    set {_txOutPublicKey = newValue}
  }
  /// Returns true if `txOutPublicKey` has been explicitly set.
  public var hasTxOutPublicKey: Bool {self._txOutPublicKey != nil}
  /// Clears the value of `txOutPublicKey`. Subsequent reads from it will return its default value.
  public mutating func clearTxOutPublicKey() {self._txOutPublicKey = nil}

  //// Any additional text explaining the gift
  public var memo: String = String()

  //// BIP39 entropy, allowing the recipient to spend the money.
  //// When deriving an AccountKey from this entropy, account_index is always 0.
  public var bip39Entropy: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _txOutPublicKey: External_CompressedRistretto? = nil
}

//// Message encoding information required to locate a TxOut,
//// un-blind the amount, and spend the TxOut. This can be used to give
//// MobileCoin to both FOG & non-FOG users who may not yet have
/// a MobileCoin account enabled
public struct Printable_TxOutGiftCode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The global index of the TxOut that has been gifted. This allows
  /// the receiver to find & uniquely identify the TxOut
  public var globalIndex: UInt64 = 0

  /// The one-time private key which can be used to spend the TxOut
  public var onetimePrivateKey: External_RistrettoPrivate {
    get {_onetimePrivateKey ?? External_RistrettoPrivate()}
    set {_onetimePrivateKey = newValue}
  }
  /// Returns true if `onetimePrivateKey` has been explicitly set.
  public var hasOnetimePrivateKey: Bool {self._onetimePrivateKey != nil}
  /// Clears the value of `onetimePrivateKey`. Subsequent reads from it will return its default value.
  public mutating func clearOnetimePrivateKey() {self._onetimePrivateKey = nil}

  /// The shared secret used to un-blind the amount of the TxOut
  public var sharedSecret: External_CompressedRistretto {
    get {_sharedSecret ?? External_CompressedRistretto()}
    set {_sharedSecret = newValue}
  }
  /// Returns true if `sharedSecret` has been explicitly set.
  public var hasSharedSecret: Bool {self._sharedSecret != nil}
  /// Clears the value of `sharedSecret`. Subsequent reads from it will return its default value.
  public mutating func clearSharedSecret() {self._sharedSecret = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _onetimePrivateKey: External_RistrettoPrivate? = nil
  fileprivate var _sharedSecret: External_CompressedRistretto? = nil
}

//// This wraps all of the above messages using "oneof", allowing us to
//// have a single encoding scheme and extend as necessary simply by adding
//// new messages without breaking backwards compatibility
public struct Printable_PrintableWrapper: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var wrapper: Printable_PrintableWrapper.OneOf_Wrapper? = nil

  public var publicAddress: External_PublicAddress {
    get {
      if case .publicAddress(let v)? = wrapper {return v}
      return External_PublicAddress()
    }
    set {wrapper = .publicAddress(newValue)}
  }

  public var paymentRequest: Printable_PaymentRequest {
    get {
      if case .paymentRequest(let v)? = wrapper {return v}
      return Printable_PaymentRequest()
    }
    set {wrapper = .paymentRequest(newValue)}
  }

  public var transferPayload: Printable_TransferPayload {
    get {
      if case .transferPayload(let v)? = wrapper {return v}
      return Printable_TransferPayload()
    }
    set {wrapper = .transferPayload(newValue)}
  }

  public var txOutGiftCode: Printable_TxOutGiftCode {
    get {
      if case .txOutGiftCode(let v)? = wrapper {return v}
      return Printable_TxOutGiftCode()
    }
    set {wrapper = .txOutGiftCode(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Wrapper: Equatable, Sendable {
    case publicAddress(External_PublicAddress)
    case paymentRequest(Printable_PaymentRequest)
    case transferPayload(Printable_TransferPayload)
    case txOutGiftCode(Printable_TxOutGiftCode)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "printable"

extension Printable_PaymentRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PaymentRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_address\0\u{1}value\0\u{1}memo\0\u{3}token_id\0\u{3}payment_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._publicAddress) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.memo) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.tokenID) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.paymentID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._publicAddress {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 2)
    }
    if !self.memo.isEmpty {
      try visitor.visitSingularStringField(value: self.memo, fieldNumber: 3)
    }
    if self.tokenID != 0 {
      try visitor.visitSingularUInt64Field(value: self.tokenID, fieldNumber: 4)
    }
    if self.paymentID != 0 {
      try visitor.visitSingularUInt64Field(value: self.paymentID, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Printable_PaymentRequest, rhs: Printable_PaymentRequest) -> Bool {
    if lhs._publicAddress != rhs._publicAddress {return false}
    if lhs.value != rhs.value {return false}
    if lhs.memo != rhs.memo {return false}
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.paymentID != rhs.paymentID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Printable_TransferPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TransferPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}root_entropy\0\u{3}tx_out_public_key\0\u{1}memo\0\u{3}bip39_entropy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.rootEntropy) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._txOutPublicKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.memo) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.bip39Entropy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.rootEntropy.isEmpty {
      try visitor.visitSingularBytesField(value: self.rootEntropy, fieldNumber: 1)
    }
    try { if let v = self._txOutPublicKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.memo.isEmpty {
      try visitor.visitSingularStringField(value: self.memo, fieldNumber: 3)
    }
    if !self.bip39Entropy.isEmpty {
      try visitor.visitSingularBytesField(value: self.bip39Entropy, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Printable_TransferPayload, rhs: Printable_TransferPayload) -> Bool {
    if lhs.rootEntropy != rhs.rootEntropy {return false}
    if lhs._txOutPublicKey != rhs._txOutPublicKey {return false}
    if lhs.memo != rhs.memo {return false}
    if lhs.bip39Entropy != rhs.bip39Entropy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Printable_TxOutGiftCode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TxOutGiftCode"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}global_index\0\u{3}onetime_private_key\0\u{3}shared_secret\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.globalIndex) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._onetimePrivateKey) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sharedSecret) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.globalIndex != 0 {
      try visitor.visitSingularUInt64Field(value: self.globalIndex, fieldNumber: 1)
    }
    try { if let v = self._onetimePrivateKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sharedSecret {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Printable_TxOutGiftCode, rhs: Printable_TxOutGiftCode) -> Bool {
    if lhs.globalIndex != rhs.globalIndex {return false}
    if lhs._onetimePrivateKey != rhs._onetimePrivateKey {return false}
    if lhs._sharedSecret != rhs._sharedSecret {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Printable_PrintableWrapper: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrintableWrapper"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_address\0\u{3}payment_request\0\u{3}transfer_payload\0\u{3}tx_out_gift_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: External_PublicAddress?
        var hadOneofValue = false
        if let current = self.wrapper {
          hadOneofValue = true
          if case .publicAddress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wrapper = .publicAddress(v)
        }
      }()
      case 2: try {
        var v: Printable_PaymentRequest?
        var hadOneofValue = false
        if let current = self.wrapper {
          hadOneofValue = true
          if case .paymentRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wrapper = .paymentRequest(v)
        }
      }()
      case 3: try {
        var v: Printable_TransferPayload?
        var hadOneofValue = false
        if let current = self.wrapper {
          hadOneofValue = true
          if case .transferPayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wrapper = .transferPayload(v)
        }
      }()
      case 4: try {
        var v: Printable_TxOutGiftCode?
        var hadOneofValue = false
        if let current = self.wrapper {
          hadOneofValue = true
          if case .txOutGiftCode(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wrapper = .txOutGiftCode(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.wrapper {
    case .publicAddress?: try {
      guard case .publicAddress(let v)? = self.wrapper else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .paymentRequest?: try {
      guard case .paymentRequest(let v)? = self.wrapper else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .transferPayload?: try {
      guard case .transferPayload(let v)? = self.wrapper else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .txOutGiftCode?: try {
      guard case .txOutGiftCode(let v)? = self.wrapper else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Printable_PrintableWrapper, rhs: Printable_PrintableWrapper) -> Bool {
    if lhs.wrapper != rhs.wrapper {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
